/*
 * Generated by dtrace(1M).
 */

#ifndef	_FALCON_PROBES_H
#define	_FALCON_PROBES_H



#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	FALCON_CLOSE() \
	__dtrace_falcon___close()
#define	FALCON_CLOSE_ENABLED() \
	__dtraceenabled_falcon___close()
#define	FALCON_OPEN() \
	__dtrace_falcon___open()
#define	FALCON_OPEN_ENABLED() \
	__dtraceenabled_falcon___open()


extern void __dtrace_falcon___close(void);
extern int __dtraceenabled_falcon___close(void);
extern void __dtrace_falcon___open(void);
extern int __dtraceenabled_falcon___open(void);

#else

#define	FALCON_CLOSE()
#define	FALCON_CLOSE_ENABLED() (0)
#define	FALCON_OPEN()
#define	FALCON_OPEN_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _FALCON_PROBES_H */
