/* Copyright (C) 2006 MySQL AB

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; version 2 of the License.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */

/*
 *	PROGRAM:		Virtual Data Manager
 *	MODULE:			nodes.h
 *	DESCRIPTION:	Language node types
 *
 * copyright (nod_c) 1997 by James A. Starkey
 */

NODE (nod_define_table, "define table")
NODE (nod_select, "select")
NODE (nod_add_field, "Add field")
NODE (nod_drop_field, "Drop field")
NODE (nod_alter_table, "Alter table")
NODE (nod_alter_field, "Alter field")
NODE (nod_alter_user, "Alter user")
NODE (nod_and, "And")
NODE (nod_or, "Or")
NODE (nod_not, "Not")
NODE (nod_create_index, "Create Index")
NODE (nod_upgrade_index, "Upgrade")
NODE (nod_unique, "Unique")
NODE (nod_primary_key, "Primary Key")
NODE (nod_create_table, "Create Table")
NODE (nod_upgrade_table, "Upgrade Table")
NODE (nod_rename_table, "Rename Table")
NODE (nod_create_view, "Create View")
NODE (nod_upgrade_view, "Upgrade View")
NODE (nod_drop_view, "Drop View")
NODE (nod_integer, "Integer")
NODE (nod_smallint, "Smallint")
NODE (nod_bigint, "Bigint")
NODE (nod_tinyint, "Tinyint")
NODE (nod_float, "float")
NODE (nod_double, "double")
NODE (nod_blob, "Blob")
NODE (nod_char, "char")
NODE (nod_text, "text")
NODE (nod_date, "date")
NODE (nod_timestamp, "timestamp")
NODE (nod_time, "time")
NODE (nod_varchar, "varchar")
NODE (nod_numeric, "numeric")
NODE (nod_decimal_number, "Decimal Number")
NODE (nod_delete, "Delete")
NODE (nod_repair, "Repair")
NODE (nod_field, "Field")
NODE (nod_not_null, "Not Null")
NODE (nod_default_value, "Default Value")
NODE (nod_searchable, "searchable")
NODE (nod_not_searchable, "not searchable")
NODE (nod_collation, "collation")
NODE (nod_foreign_key, "Foreign Key")
NODE (nod_identifier, "Identifier")
NODE (nod_record_number, "record number")
NODE (nod_insert, "Insert")
NODE (nod_replace, "Replace")
NODE (nod_name, "Name")
NODE (nod_number, "Number")
NODE (nod_order, "Order")
NODE (nod_descending, "Descending")
NODE (nod_quoted_string, "Quoted String")
NODE (nod_select_clause, "Select Clause")
NODE (nod_distinct, "Distinct")
NODE (nod_gtr, "Gtr")
NODE (nod_geq, "Geq")
NODE (nod_eql, "Eql")
NODE (nod_leq, "Leq")
NODE (nod_lss, "Lss")
NODE (nod_neq, "Neq")
NODE (nod_in_list, "in list")
NODE (nod_in_select, "in select")
NODE (nod_exists, "exists")
NODE (nod_between, "Between")
NODE (nod_like, "Like")
NODE (nod_starting, "starts with")
NODE (nod_containing, "Containing")
NODE (nod_matching, "Matching")
NODE (nod_null, "Null")
NODE (nod_parameter, "Parameter")
NODE (nod_count, "Count")
NODE (nod_sum, "sum")
NODE (nod_min, "min")
NODE (nod_max, "max")
NODE (nod_avg, "avg")
NODE (nod_create_database, "Create Database")
NODE (nod_drop_database, "Drop Database")
NODE (nod_drop_index, "Drop Index")
NODE (nod_drop_primary_key, "Drop primary key")
NODE (nod_drop_foreign_key, "Drop foreign key")
NODE (nod_drop_table, "Drop Table")
NODE (nod_open, "Open")
NODE (nod_show, "Show")
NODE (nod_close, "Close")
NODE (nod_commit, "Commit")
NODE (nod_rollback, "Rollback")
NODE (nod_table, "Table")
NODE (nod_assign, "Assign")
NODE (nod_update, "Update")
NODE (nod_list, "list")
NODE (nod_create_dataset, "Create Data set")
NODE (nod_table_data, "Table data")
NODE (nod_constant, "Constant")
NODE (nod_load, "Load")
NODE (nod_save, "Save")
NODE (nod_print, "Print")
NODE (nod_go, "Go")
NODE (nod_schema_authorization, "Schema authorization")
NODE (nod_function, "Function")
NODE (nod_grant, "Grant")
NODE (nod_grant_role, "Grant role")
NODE (nod_alter, "Alter")
NODE (nod_read, "Read")
NODE (nod_identity, "Identity")
NODE (nod_check, "Check")
NODE (nod_constraint, "Constraint")
NODE (nod_domain, "Domain")
NODE (nod_is_null, "is null")
NODE (nod_is_active_role, "is active_role")
NODE (nod_minvalue, "minvalue")
NODE (nod_maxvalue, "maxvalue")
NODE (nod_increment, "increment")
NODE (nod_start, "start with")
NODE (nod_cycle, "cycle")
NODE (nod_cache, "cache")
NODE (nod_start_server, "Start server")
NODE (nod_reindex, "reindex")
NODE (nod_cursor, "cursor")
NODE (nod_alias, "alias")
NODE (nod_push_namespace, "push_namespace")
NODE (nod_pop_namespace, "pop_namespace")
NODE (nod_set_namespace, "set_namespace")
NODE (nod_case, "case")
NODE (nod_case_search, "case_search")
NODE (nod_add, "add")
NODE (nod_subtract, "subtract")
NODE (nod_multiply, "multiply")
NODE (nod_divide, "divide")
NODE (nod_mod, "divide")
NODE (nod_negate, "negate")
NODE (nod_cast, "cast")
NODE (nod_concat, "concatenation")
NODE (nod_create_user, "create user")
NODE (nod_drop_user, "drop user")
NODE (nod_create_role, "create role")
NODE (nod_upgrade_role, "create role")
NODE (nod_drop_role, "drop role")
NODE (nod_revoke, "revoke")
NODE (nod_revoke_role, "revoke")
NODE (nod_assume, "assume")
NODE (nod_revert, "revert")
NODE (nod_priv_alter, "negate")
NODE (nod_priv_insert, "priv insert")
NODE (nod_priv_delete, "priv delete")
NODE (nod_priv_execute, "priv execute")
NODE (nod_priv_select, "priv select")
NODE (nod_priv_update, "priv update")
NODE (nod_priv_grant, "priv grant")
NODE (nod_priv_all, "priv all")
NODE (nod_role, "role")
NODE (nod_view, "view")
NODE (nod_procedure, "procedure")
NODE (nod_user, "user")
NODE (nod_coterie, "coterie")
NODE (nod_grant_option, "admin")
NODE (nod_default_role, "default role")
NODE (nod_create_sequence, "create sequence")
NODE (nod_upgrade_sequence, "upgrade sequence")
NODE (nod_drop_sequence, "drop sequence")
NODE (nod_next_value, "next value")
NODE (nod_create_trigger, "create trigger")
NODE (nod_upgrade_trigger, "upgrade trigger")
NODE (nod_alter_trigger, "alter trigger")
NODE (nod_drop_trigger, "drop trigger")
NODE (nod_pre_insert, "pre-insert")
NODE (nod_post_insert, "post-insert")
NODE (nod_pre_update, "pre-update")
NODE (nod_post_update, "post-update")
NODE (nod_pre_delete, "pre-delete")
NODE (nod_post_delete, "post-delete")
NODE (nod_pre_commit, "pre-commit")
NODE (nod_post_commit, "post-commit")
NODE (nod_active, "active")
NODE (nod_inactive, "inactive")
NODE (nod_position, "position")
NODE (nod_select_expr, "select-expr")
NODE (nod_create_filterset, "create filterset")
NODE (nod_upgrade_filterset, "upgrade filterset")
NODE (nod_drop_filterset, "drop filterset")
NODE (nod_enable_filterset, "enable filterset")
NODE (nod_disable_filterset, "disable filterset")
NODE (nod_table_filter, "table filter")
NODE (nod_left_outer, "left outer")
NODE (nod_right_outer, "right outer")
NODE (nod_full_outer, "full outer")
NODE (nod_inner, "inner")
NODE (nod_join, "join")
NODE (nod_join_term, "join_term")
NODE (nod_trigger_class, "trigger class")
NODE (nod_enable_trigger_class, "enable trigger class")
NODE (nod_disable_trigger_class, "disable trigger class")
NODE (nod_create_coterie, "create coterie")
NODE (nod_upgrade_coterie, "upgrade coterie")
NODE (nod_drop_coterie, "drop coterie")
NODE (nod_range, "range")
NODE (nod_ip_address, "ip address")
NODE (nod_node_name, "node_name")
NODE (nod_wildcard, "wildcard")
NODE (nod_log_bool, "log boolean")
NODE (nod_encrypted, "encrypted")
NODE (nod_create_repository, "create repository")
NODE (nod_upgrade_repository, "upgrade repository")
NODE (nod_drop_repository, "drop repository")
NODE (nod_repository, "repository")
NODE (nod_create_domain, "create domain")
NODE (nod_upgrade_domain, "upgrade domain")
NODE (nod_upgrade_schema, "upgrade schema")
NODE (nod_sync_repository, "sync repository")
NODE (nod_cascade_delete, "delete cascade")
NODE (nod_index_segment, "index segment")
NODE (nod_create_tablespace, "create tablespace")
NODE (nod_upgrade_tablespace, "upgrade tablespace")
NODE (nod_drop_tablespace, "drop tablespace")
