// #define PARAMETER(name, text, min, default, max, flags, function)

PARAMETER(debug_mask, "Falcon message type mask for logged messages.", 0, 0, INT_MAX, 0, NULL)
PARAMETER(debug_trace, "Falcon debug trace trigger.", 0, 0, INT_MAX, 0, NULL)
PARAMETER(io_threads, "Number of Falcon I/O threads", 2, 2, 20, 0, NULL)
PARAMETER(gopher_threads, "Number of Falcon gopher threads", 1, 5, 20, 0, NULL)
PARAMETER(large_blob_threshold, "Threshold for large blobs", 0, 160000, INT_MAX, 0, NULL)
PARAMETER(lock_timeout, "Transaction lock time period (milliseconds)", 0, 0, INT_MAX, 0, NULL)
PARAMETER(serial_log_priority, "Whether or not serial log has write priority over other writes.", 0, 1, 1, 0, NULL)
PARAMETER(direct_io, "Whether Falcon should use O_DIRECT.", 0, 1, 1, 0, NULL)
PARAMETER(serial_log_block_size, "Minimum block size for serial log.", 0, 0, 4096, 0, NULL)
